import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.io.IOException;

import static org.junit.Assert.assertEquals;
import static org.powermock.api.mockito.PowerMockito.verifyNew;
import static org.powermock.api.mockito.PowerMockito.whenNew;

@RunWith(PowerMockRunner.class)
@PrepareForTest(CharacterSheet.class)
public class TestCharacterSheet {
	String name = "Manetherin";
	CharacterSheet manny = new CharacterSheet(name);

	@Test
	public void testGetCharacterName() {
		assertEquals(manny.getCharacterName(), name);
	}

	@Test
	public void testSetCharacterName() {
		String newName = "Jonny";
		manny.setCharacterName(newName);
		assertEquals(manny.getCharacterName(), newName);
	}

	@Test
	public void testGenerateGui() throws Exception {
		whenNew(Gui.class).withNoArguments().thenThrow(new IOException("error message"));
		manny.generateGui();
		verifyNew(Gui.class).withNoArguments();
	}



































































































































































































































































































































































































































































































































































































































































































}